force-app/main/default/objects/Message__c/Message__c.object-meta.xml
<CustomObject>
    <label>Message</label>
    <nameField>
        <label>Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Message_in_Account__c/Message_in_Account__c.object-meta.xml
<CustomObject>
    <label>Message in Account</label>
    <nameField>
        <label>Message in Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Messa</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Message_in_Account__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Messa</relationshipLabel>
    <relationshipName>Messa</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Message_in_Account__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <referenceTo>Message__c</referenceTo>
    <relationshipLabel>Messa</relationshipLabel>
    <relationshipName>Messa</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/AccountMessageJunioController.cls
public with sharing class AccountMessageJunioController {
    public List<AccountWrapper> accountsWrapper {get;set;}
    public string description {get;set;}

    public AccountMessageJunioController() {
        this.accountsWrapper = new List<AccountWrapper>();

        for (Account anAccount : [
            SELECT Id, Name
            FROM Account
            LIMIT 30
        ]) {
            this.accountsWrapper.add(
                new accountWrapper(
                    anAccount
                )
            );
        }
    }

    public void save() {

        if (String.isEmpty(this.description)) {
            apexpages.addMessage(
                new ApexPages.message(
                    Apexpages.Severity.WARNING,'No se escribio una descripcion para el mensaje'
                )
            );
            return;
        }
        Savepoint sp = Database.setSavepoint();

        Message__c aMessage = new Message__c(
            Description__c = this.description
        );
        insert aMessage;

        List<Message_in_Account__c> messagesInAccounts = new List<Message_in_Account__c>();

        for (AccountWrapper anAccountWrapper : this.accountsWrapper) {
            if (anAccountWrapper.isChecked) {
                messagesInAccounts.add(
                    new Message_in_Account__c(
                        account__c = anAccountWrapper.anAccount.Id,
                        message__c = aMessage.Id
                    )
                );
            }   
        }

        if (messagesInAccounts.isEmpty()) {
            apexpages.addMessage(
                new ApexPages.message(
                    Apexpages.Severity.WARNING,'No se seleccionaron cuentas'
                )
            );
            Database.rollback(sp);
            return;
        }

        insert messagesInAccounts;
        apexpages.addMessage(
            new ApexPages.message(
                Apexpages.Severity.CONFIRM,'El mensaje fue insertado correctamente'
            )
        );
    }

    public class AccountWrapper {
        public Account anAccount {get;set;}
        public Boolean isChecked {get;set;}
        public AccountWrapper(Account anAccount){
            this.anAccount = anAccount;
            this.isChecked = false;
        }
    }
}