force-app/main/default/objects/Webservice_Endpoint_Setting__mdt/Webservice_Endpoint_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Webservice Endpoint Setting</label>
    <pluralLabel>Webservice Endpoint Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Webservice_Endpoint_Setting__mdt/fields/IsProduction__c.field-meta.xml
<CustomField>
    <fullName>IsProduction__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsProduction</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Webservice_Endpoint_Setting__mdt/fields/Pass__c.field-meta.xml
<CustomField>
    <fullName>Pass__c</fullName>
    <label>Pass</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Webservice_Endpoint_Setting__mdt/fields/TokenAPI__c.field-meta.xml
<CustomField>
    <fullName>TokenAPI__c</fullName>
    <label>TokenAPI</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ConfigUtils.cls
public with sharing class ConfigUtils {
    public static Organization currentOrg;

	public static Boolean isProductionEnviroment() {

		if (currentOrg == null) {
			currentOrg = [SELECT Id, Name, IsSandbox FROM Organization LIMIT 1];
		}

		return !currentOrg.isSandbox;
	}

	public static Webservice_Endpoint_Setting__mdt getWebServiceConfig(String wsName) {
		return [
			SELECT 
				DeveloperName, 
				URL__c, 
				IsProduction__c, 
				User__c,
				Pass__c,
				TokenAPI__c
			FROM Webservice_Endpoint_Setting__mdt
			WHERE IsProduction__c = :isProductionEnviroment()
				AND MasterLabel = :wsName
			LIMIT 1
		];
	}
}